### ISSUE TITLE
Consolidating health tracking between branches:

### ISSUE THREAD

**Issue by NumbuhFour** [fad4470/AI-Tribes#9]
This should be split into separate issues later.
- [ ] Implement strength for genetic evol.
- [ ] Roll die for each entity in combat between 0-strength. Strongest doesnt take damage.
  - [ ] Add account for attack speed
- [ ] Add property tracker to humans for health
- [ ] Stop entities (animals) rather than immediately destroy them
  - [ ] destroy after some time while dead
- [ ] Move all properties (Strength) to the property tracker
### Interactive Properties:
- [ ] Strength
- [ ] Size (bigger yields and needs more food)
- [ ] Attack Speed
